### ISSUE TITLE
Add support for SPL Token Types

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/platform#44] opened 2023-09-06 15:11 UTC
**Is your enhancement request related to a problem? Please describe.**
Trying to build a simple defi, I needed to perform checks on Mint and Token types. This includes both data and metadata checks

**Describe the solution you'd like**
To add support for these types with the built-in metadata checks + data constraints supported by Anchor, both in Anchor and Solana Native.

**Describe alternatives you've considered**
I manually placed checks inside my stubs.

**Additional context**
Metadata is referred to account len, account program owner, pda address, discriminator, mint address (maybe others?)
Data constraints is referred to token account authority, token account mint, mint authority (maybe others?)

**Comment by JazielGuerrero** [comment] 2023-12-05 02:56
Related to/Duplicate of: https://github.com/Codigo-io/platform/issues/33

**Closed by JazielGuerrero** 2023-12-05 02:56 UTC
Labels: triage, enhancement
